---
title: "Proyectos investigacion"
editor: visual
---

# 

1.  Denominación del proyecto: **Retraso maduracional y/o trayectorias de desarrollo alteradas en el Trastorno por Déficit de Atención (TDA) y en el Trastorno del Espectro Autista (TEA) través del análisis del EEG espontáneo. Una ayuda al diagnóstico PAIDI** 2020.

    **Proyectos I+D+i,** Duración: 05/10/2021 al 31/12/2022, Referencia: P20_00537, Calidad en que ha participado: Investigador/a. Importe: 59200.00€ Duración del proyecto: 452 días

2.  Denominación del proyecto: **DESARROLLO ONTOGENETICO DE LAS OCILACIONES CEREBRALES LIGADAS A LA MEMORIA DE TRABAJO. ALTERACIONES DEL DESARROLLO EN EL TDAH**. Calidad en que hE participado: Investigador/a Número de investigadores/as: 3. **Entidad/es financiadora/s:** MINISTERIO DE CIENCIA E INNOVACION Cód. según financiadora: PID2019-105618RB-I00. Fecha de inicio: 01/01/2020 Duración del proyecto: 1095 días

3.  Denominación del proyecto: **LA CARACTERIZACIÓN DE FENOTIPOS DE INATENCIÓN EN NIÑOS: LOS PERFILES CONDUCTUALES Y PSICOLÓGICOS DE SLUGGISH COGNITIVE TEMPO Y DEL TDAH.**

    Ámbito del proyecto: Nacional Calidad en que ha participado: Investigador/a Número de investigadores/as: 4. **Entidad/es financiadora/s**: FECYT-MINISTERIO DE ECONOMIA Cód. según financiadora: PSI2017-82550R Fecha de inicio: 01/01/2018 Duración del proyecto: 1338 días Cuantía total: 76.230 euros.

4.  Denominación del proyecto: **EVALUACIÓN DEL DÉFICIT ATENCIONAL EN PACIENTES CON ESCLEROSIS MÚLTIPLE**. Ámbito del proyecto: Nacional. Calidad en que ha participado: Investigador/a Investigador/es responsable/es: MANUEL VÁZQUEZ MARRUFO Número de investigadores/as: 6. Código entidad financiadora: SEJ2007-65343. Fecha de inicio: 01/10/2007 Duración del proyecto: 1095 días Cuantía total: 101.640.

5.  Denominación del proyecto: **RAPIDEZ DE PROCESAMIENTO Y ESTILOS DE VIDA EN EL DETERIORO DE LA MEMORIA: ESTUDIO LONGITUDINAL EN PERSONAS MAYORES**

    Ámbito del proyecto: NACIONAL. Investigador/es responsable/es: MANUEL MORALES ORTIZ. Número de investigadores/as: 7 **Código** **entidad financiadora:** IMSERS2005/001 Fecha de inicio: 05/12/2005 Duración del proyecto: 730 días . Cuantía total: 18.000

6.  Denominación del proyecto: **APLICACIONES DE LA TEORIA PSICOLOGICA PARA EL DISEÑO DE GRÁFICOS ESTADISTICOS.** Investigador/es responsable/es: MANUEL MORALES ORTIZ Número de investigadores/as: 4 **Cód. entidad financiadora:** PB93-1173 Fecha de inicio: 01/06/1994 Duración del proyecto: 1309 días

7.  Denominación del proyecto: **PENSAMIENTO Y LENGUAJE EN SITUACIONES DE CAMBIO CULTURAL: UNA APROXIMACIÓN ETNOMETODOLÓGICA LA DISCURSO EN LA EDUCACIÓN DE ADULTOS.** Calidad en que ha participado: Investigador/a Investigador/es responsable/es: JUAN DANIEL RAMIREZ GARRIDO Número de investigadores/as: 4 Fecha de inicio: 01/01/1989 Duración del proyecto: 1094 días

8.  Denominación del proyecto: **FOMENTO DE LAS DISPOSICION HACIA EL APRENDIZAJE MEDIANTE EL MANEJO DE LA ESTIMULACION AMBIENTAL EN EL AULA DE PREESCOLAR** Calidad en que ha participado: Investigador/a Investigador/es responsable/es: RAFAEL MORENO RODRIGUEZ Número de investigadores/as: 2 Fecha de inicio: 01/10/1984 Duración del proyecto: 395 días

9.  Denominación del proyecto: **USO RACIONAL DE LOS MEDICAMENTOS EN LA PREVENCIÓN DE LA MORBILIDAD CARDIOVASCULAR** Ámbito del proyecto: Autonómica Calidad en que ha participado: Investigador/a Investigador/es responsable/es: MARIA DEL CARMEN MONTERO BALOSA Número de investigadores/as: 2 **Cód. entidad financiadora:** 51027 Fecha de inicio: 01/01/2004 Duración del proyecto: 1095 días Cuantía total: 13.300

10. Denominación del proyecto: **EFECTOS DEL RUIDO EN TAREAS QUE REQUIEREN ATENCIÓN Y EN TEMAS DE RESOLUCIÓN DE PROBLEMAS.** Ámbito del proyecto: Autonómica Calidad en que ha participado: Investigador/a Responsable/es: LEÓN-CARRIÓN, JOSE, MORALES- ORTIZ, M. y DOMINGUEZ MORALES, R. Número de investigadores/as: 3 Fecha de inicio: 01/01/1993 Duración del proyecto: 364 días.

11. Denominación del proyecto: **EFECTOS DE LA EXPOSICIÓN A SOLVENTES ORGÁNICOS EN LA ACTIVIDAD NEUROPSICOLÓGICA DEL CEREBRO**. Ámbito del proyecto: Autonómica Calidad en que ha participado: Investigador/a Número de investigadores/as: 3 Fecha de inicio: 01/01/1996 Duración del proyecto: 364 días
